### ISSUE TITLE
Receiving ERB error

### ISSUE THREAD

**Issue by usladha** [northwestern-fsm/bcdatabase#2]
Hi,

I followed the readme as given. I get the following error

=> Booting WEBrick...
(erb):3: compile error (SyntaxError)
(erb):3: unterminated string meets end of file
(erb):3: syntax error, unexpected $end, expecting ')'
_erbout.concat(( bcdb.production :encrypted, :db ).to_s); _erbout

Can you please point me where I am erroring. The files contents are as follows

encrypted.yml =

defaults:
  adapter: mysql
  encoding: utf8
db:
  epassword: bu4P2Rny+Xm/PmlUgRgIKg==

database.yml=
<%
  require 'bcdatabase'
  bcdb = Bcdatabase.load RAILS_ROOT+'/bcdatabase/'
%>

<%= bcdb.production :encrypted, :db %>

**Comment by rsutphin** [comment]
I'm not sure why this would lead to the error you're seeing, but `Bcdatabase.load` doesn't take an argument.  If you want to change the path where the bcdatabase files are stored, set the `BCDATABASE_PATH` env var.

Also, storing encrypted bcdatabase files in your application (i.e., under RAILS_ROOT) will probably not do what you want.  The encryption key is per-machine, so they will only be decryptable on the same machine where you encrypted them.

If you have further trouble, please send me a message with a link to a gist -- it will be easier to see what's going on if the formatting of your files is preserved.

**Comment by usladha** [comment]
Hi,

Thanks for the reply.

I have removed the argument and have set the BCDATABASE_PATH env var.

My configuration is Windows XP, Rails 2.2.2, ruby 1.86.

Regarding the master key, I am planning to generate new key while deploying the application using the command line.
