### ISSUE TITLE
Error when calling "bcdatabase help"

### ISSUE THREAD

**Issue by phlegx** [northwestern-fsm/bcdatabase#4]
Hi I get the following error:

<code>
bcdatabase help
Unknown command help.
/usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.3/lib/bcdatabase/commands.rb:236:in `command_name': undefined method`underscore' for "Help":String (NoMethodError)
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.3/lib/bcdatabase/commands.rb:207:in `help'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.3/lib/bcdatabase/commands.rb:207:in`collect'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.3/lib/bcdatabase/commands.rb:207:in `help'
    from /usr/lib/ruby/gems/1.8/gems/bcdatabase-1.0.3/bin/bcdatabase:22
    from /usr/bin/bcdatabase:19:in`load'
    from /usr/bin/bcdatabase:19
</code>

any ideas what is wrong, or what I'm doing wrong?

**Comment by rsutphin** [comment]
This looks like a bug in bcdatabase 1.0.3.  If you can, try bcdatabase 1.0.2 (it only works with Rails 2).  

I'll look into this.

**Comment by phlegx** [comment]
rsutphin, thx a lot for the fast reply! 

My project is on rails 3 so I'm looking forward to the bugfix.

**Comment by phlegx** [comment]
uh sorry I clicked on close (close issue)...

**Comment by rsutphin** [comment]
Fix missing require for AS3 and add tests for the help command that was broken by its absence.  Closed by 08f910a28c84abdfbd9629cdd16872f9dc25175e.

**Comment by rsutphin** [comment]
Thanks for the report.  Let me know if you run into any other problems.

**Comment by phlegx** [comment]
Thank you for the quick fix :) 

I will let you know if other problems occur, sure!
