### ISSUE TITLE
LoadError: no such file to load -- bcdatabase

### ISSUE THREAD

**Issue by phlegx** [northwestern-fsm/bcdatabase#6]
Hi again!

I installed the gem and tired to load bcdatabase with irb and within the application both lead to the same result

<code>
irb(main):001:0> require 'bcdatabase'
LoadError: no such file to load -- bcdatabase
</code>

Any ideas what might be wrong? 

best 
phlegx

**Comment by rsutphin** [comment]
That's going to be a problem somewhere before bcdatabase — e.g., you don't have rubygems loaded, or bcdatabase isn't in your Gemfile (and you're using bundler), or even bcdatabase isn't installed in the ruby you're using.

**Comment by phlegx** [comment]
hi rsutphin,

Thanks. Yes this probably occurs since I only did a gem install bcdatabse and I didn't do it via the Gemfile and bundle install.

I will test this tomorrow with a bundle install and report back here.
